In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features':['sqrt', 'log2'],
           'n_estimators':[10,50,80,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 80, 100]},
             verbose=3)

In [11]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [12]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.050146,0.011753,0.006250,0.007654,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.846345,0.772816,0.783565,0.816531,0.771222,0.798096,0.029122,25
1,0.197216,0.007620,0.006250,0.007655,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.857824,0.788430,0.802977,0.818101,0.766158,0.806698,0.030773,18
2,0.288674,0.008542,0.015631,0.000009,squared_error,sqrt,80,"{'criterion': 'squared_error', 'max_features':...",0.865681,0.783089,0.791228,0.816316,0.776990,0.806661,0.032406,19
3,0.376367,0.011679,0.014682,0.002093,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.869650,0.791895,0.797863,0.822016,0.776455,0.811576,0.032528,4
4,0.046309,0.001994,0.000000,0.000000,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.823823,0.741904,0.773208,0.808436,0.755452,0.780565,0.031073,32
5,0.193029,0.008997,0.009376,0.007656,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.861892,0.786225,0.799194,0.815737,0.772005,0.807010,0.031005,16
6,0.342157,0.017949,0.015694,0.000192,squared_error,log2,80,"{'criterion': 'squared_error', 'max_features':...",0.855577,0.784652,0.802894,0.821028,0.774149,0.807660,0.028809,13
7,0.383505,0.007347,0.015071,0.001850,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858236,0.792180,0.798146,0.818169,0.770937,0.807534,0.029486,14
8,0.040013,0.008342,0.006250,0.007655,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.859775,0.782526,0.780146,0.802836,0.756306,0.796318,0.034991,26
9,0.188798,0.001866,0.012578,0.004185,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.857569,0.782509,0.796390,0.817463,0.770875,0.804961,0.030539,22
10,0.326519,0.017854,0.015708,0.000770,friedman_mse,sqrt,80,"{'criterion': 'friedman_mse', 'max_features': ...",0.863439,0.786401,0.779374,0.820466,0.765928,0.803122,0.035116,24
11,0.451739,0.023296,0.015901,0.000276,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.864388,0.787448,0.800618,0.820923,0.770467,0.808769,0.032340,11
12,0.076159,0.019469,0.005246,0.006624,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.852852,0.742783,0.766270,0.802865,0.759837,0.784921,0.039216,30
13,0.215726,0.026696,0.009377,0.007657,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.864451,0.790845,0.788971,0.807994,0.767020,0.803856,0.032975,23
14,0.297456,0.009993,0.015631,0.000013,friedman_mse,log2,80,"{'criterion': 'friedman_mse', 'max_features': ...",0.860428,0.792016,0.797803,0.822294,0.766816,0.807871,0.031650,12
15,0.675564,0.229039,0.036342,0.011851,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862757,0.791657,0.797151,0.821086,0.772144,0.808959,0.031098,9
16,0.254376,0.012747,0.013876,0.003212,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.834146,0.777492,0.799744,0.800873,0.759856,0.794422,0.025018,27
17,1.271200,0.038842,0.018470,0.005591,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.860792,0.790988,0.802050,0.819732,0.770918,0.808896,0.030399,10
18,2.093411,0.028072,0.029165,0.006755,absolute_error,sqrt,80,"{'criterion': 'absolute_error', 'max_features'...",0.857992,0.800805,0.802323,0.818090,0.774501,0.810742,0.027458,5
19,2.617111,0.093743,0.042614,0.011808,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.862749,0.791557,0.800200,0.821712,0.776265,0.810497,0.029975,6
20,0.273373,0.022046,0.003006,0.003695,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.828113,0.751197,0.781938,0.795243,0.781060,0.787510,0.024899,29
21,1.299738,0.087936,0.022086,0.007495,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.844925,0.784733,0.809407,0.828109,0.769976,0.807430,0.027406,15
22,2.023691,0.074294,0.032259,0.006595,absolute_error,log2,80,"{'criterion': 'absolute_error', 'max_features'...",0.864960,0.798883,0.800779,0.819299,0.774639,0.811712,0.030171,3
23,2.492283,0.057711,0.043663,0.003686,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.861966,0.792101,0.810686,0.822597,0.775388,0.812548,0.029481,1
24,0.111716,0.011021,0.009495,0.003766,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.853699,0.772905,0.778855,0.797193,0.762788,0.793088,0.032307,28
25,0.546535,0.021617,0.024051,0.006991,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858978,0.782523,0.792601,0.821955,0.770070,0.805225,0.031874,21
26,0.908907,0.050657,0.034942,0.005477,poisson,sqrt,80,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.863743,0.793265,0.796284,0.815849,0.764501,0.806728,0.032886,17
27,1.189492,0.098377,0.055410,0.017309,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.863161,0.793810,0.802782,0.823395,0.775928,0.811815,0.029880,2
28,0.147806,0.028817,0.011259,0.006376,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.835779,0.782555,0.783593,0.768963,0.746613,0.783501,0.029346,31
29,0.549703,0.010969,0.024833,0.007427,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.859832,0.793752,0.795990,0.817925,0.778236,0.809147,0.028325,8
30,0.838079,0.008950,0.034078,0.006464,poisson,log2,80,"{'criterion': 'poisson', 'max_features': 'log2...",0.867192,0.788212,0.802398,0.820183,0.770564,0.809710,0.033051,7
31,1.043269,0.046411,0.037618,0.007709,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.860299,0.782755,0.797443,0.818064,0.771078,0.805928,0.031391,20

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex_Male 0 or 1:"))
smoker_yes_input=float(input("Smoker_Yes 0 or 1:"))

Age:31
BMI:46
Children:2
Sex_Male 0 or 1:0
Smoker_Yes 0 or 1:0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[18780.83]