In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'splitter':['best', 'random'],
           'max_features':['sqrt', 'log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}:

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005962,0.003536,0.005699,0.005236,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.471744,0.619415,0.546230,0.702437,0.494815,0.566928,0.084624,15
1,0.003533,0.006112,0.003125,0.006250,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.592643,0.628603,0.591965,0.554480,0.464353,0.566409,0.056155,16
2,0.005496,0.003722,0.000000,0.000000,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.666687,0.672624,0.653749,0.568937,0.652198,0.642839,0.037746,4
3,0.003560,0.004259,0.001068,0.002137,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.725276,0.563655,0.627750,0.576974,0.485647,0.595861,0.079128,9
4,0.004727,0.005789,0.001004,0.001230,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.689304,0.571986,0.594649,0.569819,0.550424,0.595236,0.049079,10
5,0.006262,0.007669,0.000000,0.000000,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.719107,0.543446,0.576410,0.514452,0.613590,0.593401,0.071031,12
6,0.003121,0.006243,0.003150,0.004034,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.776647,0.575526,0.590781,0.480649,0.506265,0.585974,0.103861,13
7,0.007291,0.001479,0.001396,0.001143,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.532876,0.617589,0.491536,0.711475,0.616804,0.594056,0.076304,11
8,0.013268,0.003044,0.000000,0.000000,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.776371,0.620011,0.637554,0.544387,0.613637,0.638392,0.075930,5
9,0.016150,0.010562,0.003266,0.006531,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.675430,0.634368,0.598573,0.665479,0.650124,0.644795,0.026981,3
10,0.015511,0.002099,0.003125,0.006250,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.454028,0.694745,0.609014,0.673971,0.646438,0.615639,0.085757,7
11,0.015508,0.000251,0.003125,0.006250,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.762744,0.628758,0.595670,0.555477,0.643939,0.637318,0.069687,6
12,0.000726,0.001452,0.008532,0.007073,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.705039,0.643561,0.639983,0.644858,0.715928,0.669874,0.033374,1
13,0.006250,0.007655,0.000000,0.000000,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.739803,0.446971,0.587353,0.472781,0.628593,0.575101,0.106794,14
14,0.003125,0.006251,0.003125,0.006250,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.767972,0.641473,0.659030,0.622627,0.628893,0.663999,0.053454,2
15,0.001325,0.002650,0.003684,0.006068,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.652074,0.488725,0.668567,0.607721,0.610786,0.605574,0.062954,8

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex_Male 0 or 1:"))
smoker_yes_input=float(input("Smoker_Yes 0 or 1:"))

Age:29
BMI:34
Children:1
Sex_Male 0 or 1:0
Smoker_Yes 0 or 1:1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[49577.]